/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_mbl_demo_jnidemo_JniDemo */

#ifndef _Included_net_mbl_demo_jnidemo_JniDemo
#define _Included_net_mbl_demo_jnidemo_JniDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_mbl_demo_jnidemo_JniDemo
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_mbl_demo_jnidemo_JniDemo_sayHello
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
