// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package alluxio.proto.journal;

public final class Demo {
  private Demo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface OrderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:alluxio.proto.journal.Order)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .alluxio.proto.journal.AddMountPointEntry add_mount_point = 2;</code>
     */
    boolean hasAddMountPoint();
    /**
     * <code>optional .alluxio.proto.journal.AddMountPointEntry add_mount_point = 2;</code>
     */
    alluxio.proto.journal.File.AddMountPointEntry getAddMountPoint();
    /**
     * <code>optional .alluxio.proto.journal.AddMountPointEntry add_mount_point = 2;</code>
     */
    alluxio.proto.journal.File.AddMountPointEntryOrBuilder getAddMountPointOrBuilder();

    /**
     * <code>optional .alluxio.proto.journal.BlockContainerIdGeneratorEntry block_container_id_generator = 3;</code>
     */
    boolean hasBlockContainerIdGenerator();
    /**
     * <code>optional .alluxio.proto.journal.BlockContainerIdGeneratorEntry block_container_id_generator = 3;</code>
     */
    alluxio.proto.journal.Block.BlockContainerIdGeneratorEntry getBlockContainerIdGenerator();
    /**
     * <code>optional .alluxio.proto.journal.BlockContainerIdGeneratorEntry block_container_id_generator = 3;</code>
     */
    alluxio.proto.journal.Block.BlockContainerIdGeneratorEntryOrBuilder getBlockContainerIdGeneratorOrBuilder();
  }
  /**
   * Protobuf type {@code alluxio.proto.journal.Order}
   */
  public static final class Order extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:alluxio.proto.journal.Order)
      OrderOrBuilder {
    // Use Order.newBuilder() to construct.
    private Order(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Order(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Order defaultInstance;
    public static Order getDefaultInstance() {
      return defaultInstance;
    }

    public Order getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Order(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 18: {
              alluxio.proto.journal.File.AddMountPointEntry.Builder subBuilder = null;
              if (entryCase_ == 2) {
                subBuilder = ((alluxio.proto.journal.File.AddMountPointEntry) entry_).toBuilder();
              }
              entry_ = input.readMessage(alluxio.proto.journal.File.AddMountPointEntry.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((alluxio.proto.journal.File.AddMountPointEntry) entry_);
                entry_ = subBuilder.buildPartial();
              }
              entryCase_ = 2;
              break;
            }
            case 26: {
              alluxio.proto.journal.Block.BlockContainerIdGeneratorEntry.Builder subBuilder = null;
              if (entryCase_ == 3) {
                subBuilder = ((alluxio.proto.journal.Block.BlockContainerIdGeneratorEntry) entry_).toBuilder();
              }
              entry_ = input.readMessage(alluxio.proto.journal.Block.BlockContainerIdGeneratorEntry.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((alluxio.proto.journal.Block.BlockContainerIdGeneratorEntry) entry_);
                entry_ = subBuilder.buildPartial();
              }
              entryCase_ = 3;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return alluxio.proto.journal.Demo.internal_static_alluxio_proto_journal_Order_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return alluxio.proto.journal.Demo.internal_static_alluxio_proto_journal_Order_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              alluxio.proto.journal.Demo.Order.class, alluxio.proto.journal.Demo.Order.Builder.class);
    }

    public static com.google.protobuf.Parser<Order> PARSER =
        new com.google.protobuf.AbstractParser<Order>() {
      public Order parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Order(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Order> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    private int entryCase_ = 0;
    private java.lang.Object entry_;
    public enum EntryCase
        implements com.google.protobuf.Internal.EnumLite {
      ADD_MOUNT_POINT(2),
      BLOCK_CONTAINER_ID_GENERATOR(3),
      ENTRY_NOT_SET(0);
      private int value = 0;
      private EntryCase(int value) {
        this.value = value;
      }
      public static EntryCase valueOf(int value) {
        switch (value) {
          case 2: return ADD_MOUNT_POINT;
          case 3: return BLOCK_CONTAINER_ID_GENERATOR;
          case 0: return ENTRY_NOT_SET;
          default: throw new java.lang.IllegalArgumentException(
            "Value is undefined for this oneof enum.");
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public EntryCase
    getEntryCase() {
      return EntryCase.valueOf(
          entryCase_);
    }

    public static final int ADD_MOUNT_POINT_FIELD_NUMBER = 2;
    /**
     * <code>optional .alluxio.proto.journal.AddMountPointEntry add_mount_point = 2;</code>
     */
    public boolean hasAddMountPoint() {
      return entryCase_ == 2;
    }
    /**
     * <code>optional .alluxio.proto.journal.AddMountPointEntry add_mount_point = 2;</code>
     */
    public alluxio.proto.journal.File.AddMountPointEntry getAddMountPoint() {
      if (entryCase_ == 2) {
         return (alluxio.proto.journal.File.AddMountPointEntry) entry_;
      }
      return alluxio.proto.journal.File.AddMountPointEntry.getDefaultInstance();
    }
    /**
     * <code>optional .alluxio.proto.journal.AddMountPointEntry add_mount_point = 2;</code>
     */
    public alluxio.proto.journal.File.AddMountPointEntryOrBuilder getAddMountPointOrBuilder() {
      if (entryCase_ == 2) {
         return (alluxio.proto.journal.File.AddMountPointEntry) entry_;
      }
      return alluxio.proto.journal.File.AddMountPointEntry.getDefaultInstance();
    }

    public static final int BLOCK_CONTAINER_ID_GENERATOR_FIELD_NUMBER = 3;
    /**
     * <code>optional .alluxio.proto.journal.BlockContainerIdGeneratorEntry block_container_id_generator = 3;</code>
     */
    public boolean hasBlockContainerIdGenerator() {
      return entryCase_ == 3;
    }
    /**
     * <code>optional .alluxio.proto.journal.BlockContainerIdGeneratorEntry block_container_id_generator = 3;</code>
     */
    public alluxio.proto.journal.Block.BlockContainerIdGeneratorEntry getBlockContainerIdGenerator() {
      if (entryCase_ == 3) {
         return (alluxio.proto.journal.Block.BlockContainerIdGeneratorEntry) entry_;
      }
      return alluxio.proto.journal.Block.BlockContainerIdGeneratorEntry.getDefaultInstance();
    }
    /**
     * <code>optional .alluxio.proto.journal.BlockContainerIdGeneratorEntry block_container_id_generator = 3;</code>
     */
    public alluxio.proto.journal.Block.BlockContainerIdGeneratorEntryOrBuilder getBlockContainerIdGeneratorOrBuilder() {
      if (entryCase_ == 3) {
         return (alluxio.proto.journal.Block.BlockContainerIdGeneratorEntry) entry_;
      }
      return alluxio.proto.journal.Block.BlockContainerIdGeneratorEntry.getDefaultInstance();
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (entryCase_ == 2) {
        output.writeMessage(2, (alluxio.proto.journal.File.AddMountPointEntry) entry_);
      }
      if (entryCase_ == 3) {
        output.writeMessage(3, (alluxio.proto.journal.Block.BlockContainerIdGeneratorEntry) entry_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (entryCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (alluxio.proto.journal.File.AddMountPointEntry) entry_);
      }
      if (entryCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (alluxio.proto.journal.Block.BlockContainerIdGeneratorEntry) entry_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static alluxio.proto.journal.Demo.Order parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static alluxio.proto.journal.Demo.Order parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static alluxio.proto.journal.Demo.Order parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static alluxio.proto.journal.Demo.Order parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static alluxio.proto.journal.Demo.Order parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static alluxio.proto.journal.Demo.Order parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static alluxio.proto.journal.Demo.Order parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static alluxio.proto.journal.Demo.Order parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static alluxio.proto.journal.Demo.Order parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static alluxio.proto.journal.Demo.Order parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(alluxio.proto.journal.Demo.Order prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code alluxio.proto.journal.Order}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:alluxio.proto.journal.Order)
        alluxio.proto.journal.Demo.OrderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return alluxio.proto.journal.Demo.internal_static_alluxio_proto_journal_Order_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return alluxio.proto.journal.Demo.internal_static_alluxio_proto_journal_Order_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                alluxio.proto.journal.Demo.Order.class, alluxio.proto.journal.Demo.Order.Builder.class);
      }

      // Construct using alluxio.proto.journal.Demo.Order.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        entryCase_ = 0;
        entry_ = null;
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return alluxio.proto.journal.Demo.internal_static_alluxio_proto_journal_Order_descriptor;
      }

      public alluxio.proto.journal.Demo.Order getDefaultInstanceForType() {
        return alluxio.proto.journal.Demo.Order.getDefaultInstance();
      }

      public alluxio.proto.journal.Demo.Order build() {
        alluxio.proto.journal.Demo.Order result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public alluxio.proto.journal.Demo.Order buildPartial() {
        alluxio.proto.journal.Demo.Order result = new alluxio.proto.journal.Demo.Order(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (entryCase_ == 2) {
          if (addMountPointBuilder_ == null) {
            result.entry_ = entry_;
          } else {
            result.entry_ = addMountPointBuilder_.build();
          }
        }
        if (entryCase_ == 3) {
          if (blockContainerIdGeneratorBuilder_ == null) {
            result.entry_ = entry_;
          } else {
            result.entry_ = blockContainerIdGeneratorBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.entryCase_ = entryCase_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof alluxio.proto.journal.Demo.Order) {
          return mergeFrom((alluxio.proto.journal.Demo.Order)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(alluxio.proto.journal.Demo.Order other) {
        if (other == alluxio.proto.journal.Demo.Order.getDefaultInstance()) return this;
        switch (other.getEntryCase()) {
          case ADD_MOUNT_POINT: {
            mergeAddMountPoint(other.getAddMountPoint());
            break;
          }
          case BLOCK_CONTAINER_ID_GENERATOR: {
            mergeBlockContainerIdGenerator(other.getBlockContainerIdGenerator());
            break;
          }
          case ENTRY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        alluxio.proto.journal.Demo.Order parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (alluxio.proto.journal.Demo.Order) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int entryCase_ = 0;
      private java.lang.Object entry_;
      public EntryCase
          getEntryCase() {
        return EntryCase.valueOf(
            entryCase_);
      }

      public Builder clearEntry() {
        entryCase_ = 0;
        entry_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private com.google.protobuf.SingleFieldBuilder<
          alluxio.proto.journal.File.AddMountPointEntry, alluxio.proto.journal.File.AddMountPointEntry.Builder, alluxio.proto.journal.File.AddMountPointEntryOrBuilder> addMountPointBuilder_;
      /**
       * <code>optional .alluxio.proto.journal.AddMountPointEntry add_mount_point = 2;</code>
       */
      public boolean hasAddMountPoint() {
        return entryCase_ == 2;
      }
      /**
       * <code>optional .alluxio.proto.journal.AddMountPointEntry add_mount_point = 2;</code>
       */
      public alluxio.proto.journal.File.AddMountPointEntry getAddMountPoint() {
        if (addMountPointBuilder_ == null) {
          if (entryCase_ == 2) {
            return (alluxio.proto.journal.File.AddMountPointEntry) entry_;
          }
          return alluxio.proto.journal.File.AddMountPointEntry.getDefaultInstance();
        } else {
          if (entryCase_ == 2) {
            return addMountPointBuilder_.getMessage();
          }
          return alluxio.proto.journal.File.AddMountPointEntry.getDefaultInstance();
        }
      }
      /**
       * <code>optional .alluxio.proto.journal.AddMountPointEntry add_mount_point = 2;</code>
       */
      public Builder setAddMountPoint(alluxio.proto.journal.File.AddMountPointEntry value) {
        if (addMountPointBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          entry_ = value;
          onChanged();
        } else {
          addMountPointBuilder_.setMessage(value);
        }
        entryCase_ = 2;
        return this;
      }
      /**
       * <code>optional .alluxio.proto.journal.AddMountPointEntry add_mount_point = 2;</code>
       */
      public Builder setAddMountPoint(
          alluxio.proto.journal.File.AddMountPointEntry.Builder builderForValue) {
        if (addMountPointBuilder_ == null) {
          entry_ = builderForValue.build();
          onChanged();
        } else {
          addMountPointBuilder_.setMessage(builderForValue.build());
        }
        entryCase_ = 2;
        return this;
      }
      /**
       * <code>optional .alluxio.proto.journal.AddMountPointEntry add_mount_point = 2;</code>
       */
      public Builder mergeAddMountPoint(alluxio.proto.journal.File.AddMountPointEntry value) {
        if (addMountPointBuilder_ == null) {
          if (entryCase_ == 2 &&
              entry_ != alluxio.proto.journal.File.AddMountPointEntry.getDefaultInstance()) {
            entry_ = alluxio.proto.journal.File.AddMountPointEntry.newBuilder((alluxio.proto.journal.File.AddMountPointEntry) entry_)
                .mergeFrom(value).buildPartial();
          } else {
            entry_ = value;
          }
          onChanged();
        } else {
          if (entryCase_ == 2) {
            addMountPointBuilder_.mergeFrom(value);
          }
          addMountPointBuilder_.setMessage(value);
        }
        entryCase_ = 2;
        return this;
      }
      /**
       * <code>optional .alluxio.proto.journal.AddMountPointEntry add_mount_point = 2;</code>
       */
      public Builder clearAddMountPoint() {
        if (addMountPointBuilder_ == null) {
          if (entryCase_ == 2) {
            entryCase_ = 0;
            entry_ = null;
            onChanged();
          }
        } else {
          if (entryCase_ == 2) {
            entryCase_ = 0;
            entry_ = null;
          }
          addMountPointBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .alluxio.proto.journal.AddMountPointEntry add_mount_point = 2;</code>
       */
      public alluxio.proto.journal.File.AddMountPointEntry.Builder getAddMountPointBuilder() {
        return getAddMountPointFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .alluxio.proto.journal.AddMountPointEntry add_mount_point = 2;</code>
       */
      public alluxio.proto.journal.File.AddMountPointEntryOrBuilder getAddMountPointOrBuilder() {
        if ((entryCase_ == 2) && (addMountPointBuilder_ != null)) {
          return addMountPointBuilder_.getMessageOrBuilder();
        } else {
          if (entryCase_ == 2) {
            return (alluxio.proto.journal.File.AddMountPointEntry) entry_;
          }
          return alluxio.proto.journal.File.AddMountPointEntry.getDefaultInstance();
        }
      }
      /**
       * <code>optional .alluxio.proto.journal.AddMountPointEntry add_mount_point = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          alluxio.proto.journal.File.AddMountPointEntry, alluxio.proto.journal.File.AddMountPointEntry.Builder, alluxio.proto.journal.File.AddMountPointEntryOrBuilder> 
          getAddMountPointFieldBuilder() {
        if (addMountPointBuilder_ == null) {
          if (!(entryCase_ == 2)) {
            entry_ = alluxio.proto.journal.File.AddMountPointEntry.getDefaultInstance();
          }
          addMountPointBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              alluxio.proto.journal.File.AddMountPointEntry, alluxio.proto.journal.File.AddMountPointEntry.Builder, alluxio.proto.journal.File.AddMountPointEntryOrBuilder>(
                  (alluxio.proto.journal.File.AddMountPointEntry) entry_,
                  getParentForChildren(),
                  isClean());
          entry_ = null;
        }
        entryCase_ = 2;
        return addMountPointBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          alluxio.proto.journal.Block.BlockContainerIdGeneratorEntry, alluxio.proto.journal.Block.BlockContainerIdGeneratorEntry.Builder, alluxio.proto.journal.Block.BlockContainerIdGeneratorEntryOrBuilder> blockContainerIdGeneratorBuilder_;
      /**
       * <code>optional .alluxio.proto.journal.BlockContainerIdGeneratorEntry block_container_id_generator = 3;</code>
       */
      public boolean hasBlockContainerIdGenerator() {
        return entryCase_ == 3;
      }
      /**
       * <code>optional .alluxio.proto.journal.BlockContainerIdGeneratorEntry block_container_id_generator = 3;</code>
       */
      public alluxio.proto.journal.Block.BlockContainerIdGeneratorEntry getBlockContainerIdGenerator() {
        if (blockContainerIdGeneratorBuilder_ == null) {
          if (entryCase_ == 3) {
            return (alluxio.proto.journal.Block.BlockContainerIdGeneratorEntry) entry_;
          }
          return alluxio.proto.journal.Block.BlockContainerIdGeneratorEntry.getDefaultInstance();
        } else {
          if (entryCase_ == 3) {
            return blockContainerIdGeneratorBuilder_.getMessage();
          }
          return alluxio.proto.journal.Block.BlockContainerIdGeneratorEntry.getDefaultInstance();
        }
      }
      /**
       * <code>optional .alluxio.proto.journal.BlockContainerIdGeneratorEntry block_container_id_generator = 3;</code>
       */
      public Builder setBlockContainerIdGenerator(alluxio.proto.journal.Block.BlockContainerIdGeneratorEntry value) {
        if (blockContainerIdGeneratorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          entry_ = value;
          onChanged();
        } else {
          blockContainerIdGeneratorBuilder_.setMessage(value);
        }
        entryCase_ = 3;
        return this;
      }
      /**
       * <code>optional .alluxio.proto.journal.BlockContainerIdGeneratorEntry block_container_id_generator = 3;</code>
       */
      public Builder setBlockContainerIdGenerator(
          alluxio.proto.journal.Block.BlockContainerIdGeneratorEntry.Builder builderForValue) {
        if (blockContainerIdGeneratorBuilder_ == null) {
          entry_ = builderForValue.build();
          onChanged();
        } else {
          blockContainerIdGeneratorBuilder_.setMessage(builderForValue.build());
        }
        entryCase_ = 3;
        return this;
      }
      /**
       * <code>optional .alluxio.proto.journal.BlockContainerIdGeneratorEntry block_container_id_generator = 3;</code>
       */
      public Builder mergeBlockContainerIdGenerator(alluxio.proto.journal.Block.BlockContainerIdGeneratorEntry value) {
        if (blockContainerIdGeneratorBuilder_ == null) {
          if (entryCase_ == 3 &&
              entry_ != alluxio.proto.journal.Block.BlockContainerIdGeneratorEntry.getDefaultInstance()) {
            entry_ = alluxio.proto.journal.Block.BlockContainerIdGeneratorEntry.newBuilder((alluxio.proto.journal.Block.BlockContainerIdGeneratorEntry) entry_)
                .mergeFrom(value).buildPartial();
          } else {
            entry_ = value;
          }
          onChanged();
        } else {
          if (entryCase_ == 3) {
            blockContainerIdGeneratorBuilder_.mergeFrom(value);
          }
          blockContainerIdGeneratorBuilder_.setMessage(value);
        }
        entryCase_ = 3;
        return this;
      }
      /**
       * <code>optional .alluxio.proto.journal.BlockContainerIdGeneratorEntry block_container_id_generator = 3;</code>
       */
      public Builder clearBlockContainerIdGenerator() {
        if (blockContainerIdGeneratorBuilder_ == null) {
          if (entryCase_ == 3) {
            entryCase_ = 0;
            entry_ = null;
            onChanged();
          }
        } else {
          if (entryCase_ == 3) {
            entryCase_ = 0;
            entry_ = null;
          }
          blockContainerIdGeneratorBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .alluxio.proto.journal.BlockContainerIdGeneratorEntry block_container_id_generator = 3;</code>
       */
      public alluxio.proto.journal.Block.BlockContainerIdGeneratorEntry.Builder getBlockContainerIdGeneratorBuilder() {
        return getBlockContainerIdGeneratorFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .alluxio.proto.journal.BlockContainerIdGeneratorEntry block_container_id_generator = 3;</code>
       */
      public alluxio.proto.journal.Block.BlockContainerIdGeneratorEntryOrBuilder getBlockContainerIdGeneratorOrBuilder() {
        if ((entryCase_ == 3) && (blockContainerIdGeneratorBuilder_ != null)) {
          return blockContainerIdGeneratorBuilder_.getMessageOrBuilder();
        } else {
          if (entryCase_ == 3) {
            return (alluxio.proto.journal.Block.BlockContainerIdGeneratorEntry) entry_;
          }
          return alluxio.proto.journal.Block.BlockContainerIdGeneratorEntry.getDefaultInstance();
        }
      }
      /**
       * <code>optional .alluxio.proto.journal.BlockContainerIdGeneratorEntry block_container_id_generator = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          alluxio.proto.journal.Block.BlockContainerIdGeneratorEntry, alluxio.proto.journal.Block.BlockContainerIdGeneratorEntry.Builder, alluxio.proto.journal.Block.BlockContainerIdGeneratorEntryOrBuilder> 
          getBlockContainerIdGeneratorFieldBuilder() {
        if (blockContainerIdGeneratorBuilder_ == null) {
          if (!(entryCase_ == 3)) {
            entry_ = alluxio.proto.journal.Block.BlockContainerIdGeneratorEntry.getDefaultInstance();
          }
          blockContainerIdGeneratorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              alluxio.proto.journal.Block.BlockContainerIdGeneratorEntry, alluxio.proto.journal.Block.BlockContainerIdGeneratorEntry.Builder, alluxio.proto.journal.Block.BlockContainerIdGeneratorEntryOrBuilder>(
                  (alluxio.proto.journal.Block.BlockContainerIdGeneratorEntry) entry_,
                  getParentForChildren(),
                  isClean());
          entry_ = null;
        }
        entryCase_ = 3;
        return blockContainerIdGeneratorBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:alluxio.proto.journal.Order)
    }

    static {
      defaultInstance = new Order(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:alluxio.proto.journal.Order)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_proto_journal_Order_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_alluxio_proto_journal_Order_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ndemo.proto\022\025alluxio.proto.journal\032\023jou" +
      "rnal/block.proto\032\022journal/file.proto\"\265\001\n" +
      "\005Order\022D\n\017add_mount_point\030\002 \001(\0132).alluxi" +
      "o.proto.journal.AddMountPointEntryH\000\022]\n\034" +
      "block_container_id_generator\030\003 \001(\01325.all" +
      "uxio.proto.journal.BlockContainerIdGener" +
      "atorEntryH\000B\007\n\005entryB\027\n\025alluxio.proto.jo" +
      "urnal"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          alluxio.proto.journal.Block.getDescriptor(),
          alluxio.proto.journal.File.getDescriptor(),
        }, assigner);
    internal_static_alluxio_proto_journal_Order_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_alluxio_proto_journal_Order_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_alluxio_proto_journal_Order_descriptor,
        new java.lang.String[] { "AddMountPoint", "BlockContainerIdGenerator", "Entry", });
    alluxio.proto.journal.Block.getDescriptor();
    alluxio.proto.journal.File.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
